apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: nfs
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 10Gi # Ajuste conforme a necessidade
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/jhp-dev/postgres
    server: k-suporte
    readOnly: false
