---
# -- (Optional) When using Traefik, use this section
networks:
  frontend:
    external: true
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:15
    container_name: teleport
      # -- (Optional) Remove this section, when using Traefik
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    # -- (Optional) Traefik example configuration
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.teleport.loadbalancer.server.port=3080"
      - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
      - "traefik.http.routers.teleport-http.entrypoints=web"
      - "traefik.http.routers.teleport-http.rule=HostRegexp(`teleport-demo-1.srv-prod-3.jpit.com.br`, `{subhost:[a-z]+}.teleport-demo-1.srv-prod-3.jpit.com.br`)"
      - "traefik.http.routers.teleport-https.entrypoints=websecure"
      - "traefik.http.routers.teleport-https.rule=HostRegexp(`teleport-demo-1.srv-prod-3.jpit.com.br`, `{subhost:[a-z]+}.teleport-demo-1.srv-prod-3.jpit.com.br`)"
      - "traefik.http.routers.teleport-https.tls=true"
      - "traefik.http.routers.teleport-https.tls.certresolver=staging"
      - "traefik.http.routers.teleport-https.tls.domains[0].main=teleport-demo-1.srv-prod-3.jpit.com.br"
      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.teleport-demo-1.srv-prod-3.jpit.com.br"
    networks:
      - frontend
    restart: unless-stopped